config/routes.rb
Rails.application.routes.draw do
  resources :restaurants do
    resources :reviews
  end
  #resources :restaurants, only: [:index, :show, :new, :create] do
    #resources :reviews, only: [:new, :create]
  #end
end
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  #resources :reviews, only: [:destroy]

  # Defines the root path route ("/")
  # root "articles#index"

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
  has_many :reviews, dependent: :destroy
  CATEGORY = ['chinese', 'italian', 'japanese', 'french', 'belgian']

  validates :name, :address, :category, presence: true
  validates :category, inclusion: { in: CATEGORY }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true }
  validates :rating, inclusion: { in: 0..5 }
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  def index
    @restaurants = Restaurant.all
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)
    @restaurant.save
    redirect_to restaurants_path(@restaurant)
  end

  def show
    @restaurant = Restaurant.find(params[:id])
    #@reviews = Review.where(restaurant_id: params[:id])
  end

  private

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :rating, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController

  def new
    @review = Review.new
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def create
    @review = Review.new(review_params)
    @review.save
    redirect_to restaurants_path(@restaurant)
  end

  private

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/index.html.erb
<h1>Restaurants <h1>

<ul>
  <% @restaurants.each do |restaurant| %>
    <li><%=restaurant.name %>
    <%= restaurant.category %>
    <%= restaurant.address %></li>
  <% end %>
</ul>

<%= link_to 'Add new restaurant', new_restaurant_path %>

app/views/restaurants/new.html.erb
<%= simple_form_for @restaurant do |f| %>
  <%= f.input :name %>
  <%= f.input :address, input_html: { class: "address-input" }, label_html: { class: "address-label" } %>
  <%= f.input :category, collection: Restaurant::CATEGORY %>
  <%= f.submit "Create new restaurant", class: "btn btn-primary" %>
<% end %>

app/views/restaurants/show.html.erb
<h2><%= @restaurant.name %></h2>
<p><%= @restaurant.address %></p>
<p><%= @restaurant.category %></p>

<p><strong>Reviews</strong></p>

app/views/reviews/new.html.erb
<h1> NEW review </h1>

 <%= simple_form_for[@restaurant, @review] do |f| %>
  <%= f.input  :content %>
  <%= f.input  :rating %>
  <%= f.submit 'submit review', class: 'btn btn-primary' %>
 <% end %>